using UnityEditor;
using UnityEngine;

namespace RampGenerator
{
    public class RampDrawer : MaterialPropertyDrawer
    {

        public RampDrawer()
        {

        }

        public override float GetPropertyHeight(MaterialProperty prop, string label, MaterialEditor editor)
        {
            return base.GetPropertyHeight(prop, label, editor);
        }

        public override void OnGUI(Rect position, MaterialProperty prop, string label, MaterialEditor editor)
        {
            // tex input
            var texRect = position;
            texRect.width = 100;
            editor.TexturePropertyMiniThumbnail(texRect, prop, label, "It should be generated by the Gradient Texture Window");

            //edit button
            var buttonRect = texRect;
            float btnWidth = 65;
            buttonRect.x = position.width + position.x - btnWidth;
            buttonRect.width = btnWidth;
            if (GUI.Button(buttonRect, "Edit"))
            {
                if (prop.textureValue != null)
                {
                    GradientTextureEditorWindow.ShowWindow((Texture2D)prop.textureValue);
                }
                else
                {
                    GradientTextureEditorWindow.ShowWindow();
                }
            }
        }
    }
}
